# Generated by mc-utilities

try { sh -c "find . -name .DS_Store -print -delete" }
catch {
    try { bash -c "find . -name .DS_Store -print -delete" }
    catch { echo "Deleting .DS_Store files failed, probably not on a linux based OS" }
}

New-Item -ItemType Directory -Force -Path "./out"
Remove-Item -Recurse -Force "./out/*"

### Base pack
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/DsPvPv2"

# Bedrock edition
Get-ChildItem -Path "./out/DsPvPv2/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 Bedrock.zip"
Move-Item "./out/DsPvPv2 Bedrock.zip" "./out/DsPvPv2 Bedrock.mcpack"
Get-ChildItem -Path "./out/DsPvPv2/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/DsPvPv2/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 Java.zip"

### Variation DsPvPv2 (Long Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/DsPvPv2 (Long Swords)"
Copy-Item -Path "./variation_files/long_swords/*" -Force -Recurse -Destination "./out/DsPvPv2 (Long Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/DsPvPv2 (Long Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Long Swords) Bedrock.zip"
Move-Item "./out/DsPvPv2 (Long Swords) Bedrock.zip" "./out/DsPvPv2 (Long Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/DsPvPv2 (Long Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Long Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/DsPvPv2 (Long Swords)/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Long Swords) Java.zip"

### Variation DsPvPv2 (Short Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/DsPvPv2 (Short Swords)"
Copy-Item -Path "./variation_files/short_swords/*" -Force -Recurse -Destination "./out/DsPvPv2 (Short Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/DsPvPv2 (Short Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Short Swords) Bedrock.zip"
Move-Item "./out/DsPvPv2 (Short Swords) Bedrock.zip" "./out/DsPvPv2 (Short Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/DsPvPv2 (Short Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Short Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/DsPvPv2 (Short Swords)/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Short Swords) Java.zip"

### Variation DsPvPv2 (Short Swords and Short Guards)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/DsPvPv2 (Short Swords and Short Guards)"
Copy-Item -Path "./variation_files/short_swords_guard/*" -Force -Recurse -Destination "./out/DsPvPv2 (Short Swords and Short Guards)/"

# Bedrock edition
Get-ChildItem -Path "./out/DsPvPv2 (Short Swords and Short Guards)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Short Swords and Short Guards) Bedrock.zip"
Move-Item "./out/DsPvPv2 (Short Swords and Short Guards) Bedrock.zip" "./out/DsPvPv2 (Short Swords and Short Guards) Bedrock.mcpack"
Get-ChildItem -Path "./out/DsPvPv2 (Short Swords and Short Guards)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Short Swords and Short Guards) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/DsPvPv2 (Short Swords and Short Guards)/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Short Swords and Short Guards) Java.zip"

### Variation DsPvPv2 (Medium Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/DsPvPv2 (Medium Swords)"
Copy-Item -Path "./variation_files/medium_swords/*" -Force -Recurse -Destination "./out/DsPvPv2 (Medium Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/DsPvPv2 (Medium Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Medium Swords) Bedrock.zip"
Move-Item "./out/DsPvPv2 (Medium Swords) Bedrock.zip" "./out/DsPvPv2 (Medium Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/DsPvPv2 (Medium Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Medium Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/DsPvPv2 (Medium Swords)/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Medium Swords) Java.zip"

### Variation DsPvPv2 (Henry's 1.14 default edit Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/DsPvPv2 (Henry's 1.14 default edit Swords)"
Copy-Item -Path "./variation_files/henry_swords/*" -Force -Recurse -Destination "./out/DsPvPv2 (Henry's 1.14 default edit Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/DsPvPv2 (Henry's 1.14 default edit Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Henry's 1.14 default edit Swords) Bedrock.zip"
Move-Item "./out/DsPvPv2 (Henry's 1.14 default edit Swords) Bedrock.zip" "./out/DsPvPv2 (Henry's 1.14 default edit Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/DsPvPv2 (Henry's 1.14 default edit Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Henry's 1.14 default edit Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/DsPvPv2 (Henry's 1.14 default edit Swords)/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Henry's 1.14 default edit Swords) Java.zip"

### Variation DsPvPv2 (Azula Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/DsPvPv2 (Azula Swords)"
Copy-Item -Path "./variation_files/azula_swords/*" -Force -Recurse -Destination "./out/DsPvPv2 (Azula Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/DsPvPv2 (Azula Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Azula Swords) Bedrock.zip"
Move-Item "./out/DsPvPv2 (Azula Swords) Bedrock.zip" "./out/DsPvPv2 (Azula Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/DsPvPv2 (Azula Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Azula Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/DsPvPv2 (Azula Swords)/" | Compress-Archive -Force -DestinationPath "./out/DsPvPv2 (Azula Swords) Java.zip"
