# Generated by mc-utilities

try { sh -c "find . -name .DS_Store -print -delete" }
catch {
    try { bash -c "find . -name .DS_Store -print -delete" }
    catch { echo "Deleting .DS_Store files failed, probably not on a linux based OS" }
}

New-Item -ItemType Directory -Force -Path "./out"
Remove-Item -Recurse -Force "./out/*"

### Base pack
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault Bedrock.zip"
Move-Item "./out/vanillafault Bedrock.zip" "./out/vanillafault Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault/" | Compress-Archive -Force -DestinationPath "./out/vanillafault Java.zip"

### Variation vanillafault (Long Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault (Long Swords)"
Copy-Item -Path "./variation_files/long_swords/*" -Force -Recurse -Destination "./out/vanillafault (Long Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault (Long Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Long Swords) Bedrock.zip"
Move-Item "./out/vanillafault (Long Swords) Bedrock.zip" "./out/vanillafault (Long Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault (Long Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Long Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault (Long Swords)/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Long Swords) Java.zip"

### Variation vanillafault (Short Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault (Short Swords)"
Copy-Item -Path "./variation_files/short_swords/*" -Force -Recurse -Destination "./out/vanillafault (Short Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault (Short Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Short Swords) Bedrock.zip"
Move-Item "./out/vanillafault (Short Swords) Bedrock.zip" "./out/vanillafault (Short Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault (Short Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Short Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault (Short Swords)/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Short Swords) Java.zip"

### Variation vanillafault (Short Swords and Short Guards)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault (Short Swords and Short Guards)"
Copy-Item -Path "./variation_files/short_swords_guard/*" -Force -Recurse -Destination "./out/vanillafault (Short Swords and Short Guards)/"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault (Short Swords and Short Guards)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Short Swords and Short Guards) Bedrock.zip"
Move-Item "./out/vanillafault (Short Swords and Short Guards) Bedrock.zip" "./out/vanillafault (Short Swords and Short Guards) Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault (Short Swords and Short Guards)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Short Swords and Short Guards) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault (Short Swords and Short Guards)/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Short Swords and Short Guards) Java.zip"

### Variation vanillafault (Medium Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault (Medium Swords)"
Copy-Item -Path "./variation_files/medium_swords/*" -Force -Recurse -Destination "./out/vanillafault (Medium Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault (Medium Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Medium Swords) Bedrock.zip"
Move-Item "./out/vanillafault (Medium Swords) Bedrock.zip" "./out/vanillafault (Medium Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault (Medium Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Medium Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault (Medium Swords)/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Medium Swords) Java.zip"

### Variation vanillafault (Henry's 1.14 default edit Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault (Henry's 1.14 default edit Swords)"
Copy-Item -Path "./variation_files/henry_swords/*" -Force -Recurse -Destination "./out/vanillafault (Henry's 1.14 default edit Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault (Henry's 1.14 default edit Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Henry's 1.14 default edit Swords) Bedrock.zip"
Move-Item "./out/vanillafault (Henry's 1.14 default edit Swords) Bedrock.zip" "./out/vanillafault (Henry's 1.14 default edit Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault (Henry's 1.14 default edit Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Henry's 1.14 default edit Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault (Henry's 1.14 default edit Swords)/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Henry's 1.14 default edit Swords) Java.zip"

### Variation vanillafault (Azula Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault (Azula Swords)"
Copy-Item -Path "./variation_files/azula_swords/*" -Force -Recurse -Destination "./out/vanillafault (Azula Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault (Azula Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Azula Swords) Bedrock.zip"
Move-Item "./out/vanillafault (Azula Swords) Bedrock.zip" "./out/vanillafault (Azula Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault (Azula Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Azula Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault (Azula Swords)/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Azula Swords) Java.zip"

### Variation vanillafault (Dystel Swords)
Copy-Item -Path "./pack/" -Force -Recurse -Destination "./out/vanillafault (Dystel Swords)"
Copy-Item -Path "./variation_files/dystel_swords/*" -Force -Recurse -Destination "./out/vanillafault (Dystel Swords)/"

# Bedrock edition
Get-ChildItem -Path "./out/vanillafault (Dystel Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Dystel Swords) Bedrock.zip"
Move-Item "./out/vanillafault (Dystel Swords) Bedrock.zip" "./out/vanillafault (Dystel Swords) Bedrock.mcpack"
Get-ChildItem -Path "./out/vanillafault (Dystel Swords)/assets/minecraft/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Dystel Swords) Bedrock.zip"

# Java edition
Get-ChildItem -Path "./out/vanillafault (Dystel Swords)/" | Compress-Archive -Force -DestinationPath "./out/vanillafault (Dystel Swords) Java.zip"
