:: Generated by mc-utilities

@echo off

set PACK_NAME=vanillafault

title %PACK_NAME% Java Edition Installation

cd /D "%~dp0"

set RESOURCE_FOLDER=%APPDATA%\.minecraft\resourcepacks

echo 				.
echo ==============================
echo Making resource pack folders...
echo ==============================
echo 				.

md "%RESOURCE_FOLDER%"

:: :: Base pack
rd /S /Q "%RESOURCE_FOLDER%/%PACK_NAME%"
rd /S /Q "%RESOURCE_FOLDER%/%PACK_NAME%"

md "%RESOURCE_FOLDER%/%PACK_NAME%"

:: :: Variation vanillafault (Long Swords)
rm -R "%RESOURCE_FOLDER%/vanillafault (Long Swords)"

md "%RESOURCE_FOLDER%/vanillafault (Long Swords)"

:: :: Variation vanillafault (Short Swords)
rm -R "%RESOURCE_FOLDER%/vanillafault (Short Swords)"

md "%RESOURCE_FOLDER%/vanillafault (Short Swords)"

:: :: Variation vanillafault (Short Swords and Short Guards)
rm -R "%RESOURCE_FOLDER%/vanillafault (Short Swords and Short Guards)"

md "%RESOURCE_FOLDER%/vanillafault (Short Swords and Short Guards)"

:: :: Variation vanillafault (Medium Swords)
rm -R "%RESOURCE_FOLDER%/vanillafault (Medium Swords)"

md "%RESOURCE_FOLDER%/vanillafault (Medium Swords)"

:: :: Variation vanillafault (Henry's 1.14 default edit Swords)
rm -R "%RESOURCE_FOLDER%/vanillafault (Henry's 1.14 default edit Swords)"

md "%RESOURCE_FOLDER%/vanillafault (Henry's 1.14 default edit Swords)"

:: :: Variation vanillafault (Azula Swords)
rm -R "%RESOURCE_FOLDER%/vanillafault (Azula Swords)"

md "%RESOURCE_FOLDER%/vanillafault (Azula Swords)"

:: :: Variation vanillafault (Dystel Swords)
rm -R "%RESOURCE_FOLDER%/vanillafault (Dystel Swords)"

md "%RESOURCE_FOLDER%/vanillafault (Dystel Swords)"

echo
echo ==============================
echo Copying the files...
echo ==============================
echo

:: :: Base pack
robocopy /S /V /MIR "%~dp0/out/vanillafault/." "%RESOURCE_FOLDER%/%PACK_NAME%"

:: :: Variation vanillafault (Long Swords)
robocopy /S /V /MIR "%~dp0/out/vanillafault (Long Swords)/." "%RESOURCE_FOLDER%/vanillafault (Long Swords)"

:: :: Variation vanillafault (Short Swords)
robocopy /S /V /MIR "%~dp0/out/vanillafault (Short Swords)/." "%RESOURCE_FOLDER%/vanillafault (Short Swords)"

:: :: Variation vanillafault (Short Swords and Short Guards)
robocopy /S /V /MIR "%~dp0/out/vanillafault (Short Swords and Short Guards)/." "%RESOURCE_FOLDER%/vanillafault (Short Swords and Short Guards)"

:: :: Variation vanillafault (Medium Swords)
robocopy /S /V /MIR "%~dp0/out/vanillafault (Medium Swords)/." "%RESOURCE_FOLDER%/vanillafault (Medium Swords)"

:: :: Variation vanillafault (Henry's 1.14 default edit Swords)
robocopy /S /V /MIR "%~dp0/out/vanillafault (Henry's 1.14 default edit Swords)/." "%RESOURCE_FOLDER%/vanillafault (Henry's 1.14 default edit Swords)"

:: :: Variation vanillafault (Azula Swords)
robocopy /S /V /MIR "%~dp0/out/vanillafault (Azula Swords)/." "%RESOURCE_FOLDER%/vanillafault (Azula Swords)"

:: :: Variation vanillafault (Dystel Swords)
robocopy /S /V /MIR "%~dp0/out/vanillafault (Dystel Swords)/." "%RESOURCE_FOLDER%/vanillafault (Dystel Swords)"

echo Done!

echo 				.

title Finished installing!

pause