#!/usr/bin/env bash

# Generated by mc-utilities

find . -name .DS_Store -print -delete

PACK_NAME="DsPvPv2"

# Set window title. This is complicated on linux
echo -ne "\033]0;$PACK_NAME Java Edition Installation\007"

cd "$PWD"

MINECRAFT_FOLDER="$HOME/.minecraft"

if [[ "$OSTYPE" == "darwin"* ]]; then
    MINECRAFT_FOLDER="$HOME/Library/Application Support/minecraft"
fi

RESOURCE_FOLDER="$MINECRAFT_FOLDER/resourcepacks"

echo
echo ==============================
echo Making resource pack folders...
echo ==============================
echo

mkdir "$RESOURCE_FOLDER"

### Base pack
rm -R "$RESOURCE_FOLDER/$PACK_NAME"

mkdir "$RESOURCE_FOLDER/$PACK_NAME"

### Variation DsPvPv2 (Long Swords)
rm -R "$RESOURCE_FOLDER/DsPvPv2 (Long Swords)"

mkdir "$RESOURCE_FOLDER/DsPvPv2 (Long Swords)"

### Variation DsPvPv2 (Short Swords)
rm -R "$RESOURCE_FOLDER/DsPvPv2 (Short Swords)"

mkdir "$RESOURCE_FOLDER/DsPvPv2 (Short Swords)"

### Variation DsPvPv2 (Short Swords and Short Guards)
rm -R "$RESOURCE_FOLDER/DsPvPv2 (Short Swords and Short Guards)"

mkdir "$RESOURCE_FOLDER/DsPvPv2 (Short Swords and Short Guards)"

### Variation DsPvPv2 (Medium Swords)
rm -R "$RESOURCE_FOLDER/DsPvPv2 (Medium Swords)"

mkdir "$RESOURCE_FOLDER/DsPvPv2 (Medium Swords)"

### Variation DsPvPv2 (Henry's 1.14 default edit Swords)
rm -R "$RESOURCE_FOLDER/DsPvPv2 (Henry's 1.14 default edit Swords)"

mkdir "$RESOURCE_FOLDER/DsPvPv2 (Henry's 1.14 default edit Swords)"

### Variation DsPvPv2 (Azula Swords)
rm -R "$RESOURCE_FOLDER/DsPvPv2 (Azula Swords)"

mkdir "$RESOURCE_FOLDER/DsPvPv2 (Azula Swords)"

echo
echo ==============================
echo Copying the files...
echo ==============================
echo

### Base pack
cp -v -f -R "$PWD/out/DsPvPv2/." "$RESOURCE_FOLDER/$PACK_NAME"

### Variation DsPvPv2 (Long Swords)
cp -v -f -R "$PWD/out/DsPvPv2 (Long Swords)/." "$RESOURCE_FOLDER/DsPvPv2 (Long Swords)"

### Variation DsPvPv2 (Short Swords)
cp -v -f -R "$PWD/out/DsPvPv2 (Short Swords)/." "$RESOURCE_FOLDER/DsPvPv2 (Short Swords)"

### Variation DsPvPv2 (Short Swords and Short Guards)
cp -v -f -R "$PWD/out/DsPvPv2 (Short Swords and Short Guards)/." "$RESOURCE_FOLDER/DsPvPv2 (Short Swords and Short Guards)"

### Variation DsPvPv2 (Medium Swords)
cp -v -f -R "$PWD/out/DsPvPv2 (Medium Swords)/." "$RESOURCE_FOLDER/DsPvPv2 (Medium Swords)"

### Variation DsPvPv2 (Henry's 1.14 default edit Swords)
cp -v -f -R "$PWD/out/DsPvPv2 (Henry's 1.14 default edit Swords)/." "$RESOURCE_FOLDER/DsPvPv2 (Henry's 1.14 default edit Swords)"

### Variation DsPvPv2 (Azula Swords)
cp -v -f -R "$PWD/out/DsPvPv2 (Azula Swords)/." "$RESOURCE_FOLDER/DsPvPv2 (Azula Swords)"

echo
echo Done!
echo

# Set window title. This is complicated on linux
echo -ne "\033]0;Finished installing!\007"

read -p "Press enter/return to exit . . ."