:: Generated by mc-utilities

@echo off

set PACK_NAME=DsPvPv2

title %PACK_NAME% Java Edition Installation

cd /D "%~dp0"

set RESOURCE_FOLDER=%APPDATA%\.minecraft\resourcepacks

echo 				.
echo ==============================
echo Making resource pack folders...
echo ==============================
echo 				.

md "%RESOURCE_FOLDER%"

:: :: Base pack
rd /S /Q "%RESOURCE_FOLDER%/%PACK_NAME%"
rd /S /Q "%RESOURCE_FOLDER%/%PACK_NAME%"

md "%RESOURCE_FOLDER%/%PACK_NAME%"

:: :: Variation DsPvPv2 (Long Swords)
rm -R "%RESOURCE_FOLDER%/DsPvPv2 (Long Swords)"

md "%RESOURCE_FOLDER%/DsPvPv2 (Long Swords)"

:: :: Variation DsPvPv2 (Short Swords)
rm -R "%RESOURCE_FOLDER%/DsPvPv2 (Short Swords)"

md "%RESOURCE_FOLDER%/DsPvPv2 (Short Swords)"

:: :: Variation DsPvPv2 (Short Swords and Short Guards)
rm -R "%RESOURCE_FOLDER%/DsPvPv2 (Short Swords and Short Guards)"

md "%RESOURCE_FOLDER%/DsPvPv2 (Short Swords and Short Guards)"

:: :: Variation DsPvPv2 (Medium Swords)
rm -R "%RESOURCE_FOLDER%/DsPvPv2 (Medium Swords)"

md "%RESOURCE_FOLDER%/DsPvPv2 (Medium Swords)"

:: :: Variation DsPvPv2 (Henry's 1.14 default edit Swords)
rm -R "%RESOURCE_FOLDER%/DsPvPv2 (Henry's 1.14 default edit Swords)"

md "%RESOURCE_FOLDER%/DsPvPv2 (Henry's 1.14 default edit Swords)"

:: :: Variation DsPvPv2 (Azula Swords)
rm -R "%RESOURCE_FOLDER%/DsPvPv2 (Azula Swords)"

md "%RESOURCE_FOLDER%/DsPvPv2 (Azula Swords)"

echo
echo ==============================
echo Copying the files...
echo ==============================
echo

:: :: Base pack
robocopy /S /V /MIR "%~dp0/out/DsPvPv2/." "%RESOURCE_FOLDER%/%PACK_NAME%"

:: :: Variation DsPvPv2 (Long Swords)
robocopy /S /V /MIR "%~dp0/out/DsPvPv2 (Long Swords)/." "%RESOURCE_FOLDER%/DsPvPv2 (Long Swords)"

:: :: Variation DsPvPv2 (Short Swords)
robocopy /S /V /MIR "%~dp0/out/DsPvPv2 (Short Swords)/." "%RESOURCE_FOLDER%/DsPvPv2 (Short Swords)"

:: :: Variation DsPvPv2 (Short Swords and Short Guards)
robocopy /S /V /MIR "%~dp0/out/DsPvPv2 (Short Swords and Short Guards)/." "%RESOURCE_FOLDER%/DsPvPv2 (Short Swords and Short Guards)"

:: :: Variation DsPvPv2 (Medium Swords)
robocopy /S /V /MIR "%~dp0/out/DsPvPv2 (Medium Swords)/." "%RESOURCE_FOLDER%/DsPvPv2 (Medium Swords)"

:: :: Variation DsPvPv2 (Henry's 1.14 default edit Swords)
robocopy /S /V /MIR "%~dp0/out/DsPvPv2 (Henry's 1.14 default edit Swords)/." "%RESOURCE_FOLDER%/DsPvPv2 (Henry's 1.14 default edit Swords)"

:: :: Variation DsPvPv2 (Azula Swords)
robocopy /S /V /MIR "%~dp0/out/DsPvPv2 (Azula Swords)/." "%RESOURCE_FOLDER%/DsPvPv2 (Azula Swords)"

echo Done!

echo 				.

title Finished installing!

pause